// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    Heading: typeof import('./src/components/Heading.vue')['default']
    Image: typeof import('./src/components/Image.vue')['default']
    MovieList: typeof import('./src/components/MovieList.vue')['default']
    MovieListItem: typeof import('./src/components/MovieListItem.vue')['default']
    MovieSlide: typeof import('./src/components/MovieSlide.vue')['default']
    MovieSlider: typeof import('./src/components/MovieSlider.vue')['default']
    NewsSlide: typeof import('./src/components/NewsSlide.vue')['default']
    NewsSlider: typeof import('./src/components/NewsSlider.vue')['default']
    Preloader: typeof import('./src/components/Preloader.vue')['default']
    StreamingSlider: typeof import('./src/components/StreamingSlider.vue')['default']
    Tab: typeof import('./src/components/Tab.vue')['default']
    Tabs: typeof import('./src/components/Tabs.vue')['default']
    GsIcon: typeof import('./src/components/Icons/GsIcon.vue')['default']
    GsIconRegistry: typeof import('./src/components/Icons/GsIconRegistry.vue')['default']
    WhatToWatchButton: typeof import('./src/components/WhatToWatchButton/WhatToWatchButton.vue')['default']
    DefaultPage: typeof import('./src/components/layout/DefaultPage.vue')['default']
    Page: typeof import('./src/components/layout/Page.vue')['default']
  }
}

export { }
